name: GHA
on:
  pull_request:
    branches:
      - main

jobs:
  check-signed-commits:
    name: Check signed commits
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Check sign-off
        uses: KineticCafe/actions-dco@v1

      - name: Commit if DCO failed
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':x: DCO check failed.\n\nHi @${{ github.event.pull_request.user.login }}, please sign off all commits with:\n```\ngit commit -s\n```\nIf pull request commits are not signed off, the pull request cannot be merged. For more information about why this is required, please see https://debezium.io/blog/2025/12/12/contribution-requirements-changing/[our blog] about contribution requirement changes.'
            })

  file_changes:
    name: "Detect repository changes"
    runs-on: ubuntu-latest
    needs: [ check-signed-commits ]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get modified files (Common)
        id: changed-files-common
        uses: tj-actions/changed-files@v47.0.1