name: GHA
on:
  pull_request:
    branches:
      - main

jobs:
  check-signed-commits:
    name: Check signed commits
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/check-dco

  file_changes:
    name: "Detect repository changes"
    runs-on: ubuntu-latest
    needs: [ check-signed-commits ]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get modified files (Common)
        id: changed-files-common
        uses: tj-actions/changed-files@v47.0.1